#theme: jekyll-theme-leap-day
remote-theme: "mmistakes/minimal-mistakes@4.15.1"
title: SSDBM 2019
description: 31st International Conference on Scientific and Statistical Database Management
plugins: ['jekyll-include-cache']
