theme: jekyll-theme-leap-day
title: SSDBM 2019
description: 31st International Conference on Scientific and Statistical Database Management
twitter_username: ssdbm2019
logo: Images/ssdbm.logo.2019.png
